/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserGroupAssignedForLocalTenantDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AllUserGroupsAssignedForLocalTenantDTO
 */
public class AllUserGroupsAssignedForLocalTenantDTOTest {
    private final AllUserGroupsAssignedForLocalTenantDTO model = new AllUserGroupsAssignedForLocalTenantDTO();

    /**
     * Model tests for AllUserGroupsAssignedForLocalTenantDTO
     */
    @Test
    public void testAllUserGroupsAssignedForLocalTenantDTO() {
        // TODO: test AllUserGroupsAssignedForLocalTenantDTO
    }

    /**
     * Test the property 'assignedUserGroups'
     */
    @Test
    public void assignedUserGroupsTest() {
        // TODO: test assignedUserGroups
    }

}
