/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PermissionResponseDTO
 */
public class PermissionResponseDTOTest {
    private final PermissionResponseDTO model = new PermissionResponseDTO();

    /**
     * Model tests for PermissionResponseDTO
     */
    @Test
    public void testPermissionResponseDTO() {
        // TODO: test PermissionResponseDTO
    }

    /**
     * Test the property 'permissionId'
     */
    @Test
    public void permissionIdTest() {
        // TODO: test permissionId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
