/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AdditionalCapabilitiesDTO;
import com.konfigthis.client.model.CapabilitiesDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProfileAssignedForLocalTenantDTO
 */
public class ProfileAssignedForLocalTenantDTOTest {
    private final ProfileAssignedForLocalTenantDTO model = new ProfileAssignedForLocalTenantDTO();

    /**
     * Model tests for ProfileAssignedForLocalTenantDTO
     */
    @Test
    public void testProfileAssignedForLocalTenantDTO() {
        // TODO: test ProfileAssignedForLocalTenantDTO
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'validityStartTime'
     */
    @Test
    public void validityStartTimeTest() {
        // TODO: test validityStartTime
    }

    /**
     * Test the property 'validityEndTime'
     */
    @Test
    public void validityEndTimeTest() {
        // TODO: test validityEndTime
    }

    /**
     * Test the property 'capabilities'
     */
    @Test
    public void capabilitiesTest() {
        // TODO: test capabilities
    }

    /**
     * Test the property 'additionalCapabilities'
     */
    @Test
    public void additionalCapabilitiesTest() {
        // TODO: test additionalCapabilities
    }

}
