/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserGroupAssignedForLocalTenantDTO
 */
public class UserGroupAssignedForLocalTenantDTOTest {
    private final UserGroupAssignedForLocalTenantDTO model = new UserGroupAssignedForLocalTenantDTO();

    /**
     * Model tests for UserGroupAssignedForLocalTenantDTO
     */
    @Test
    public void testUserGroupAssignedForLocalTenantDTO() {
        // TODO: test UserGroupAssignedForLocalTenantDTO
    }

    /**
     * Test the property 'userGroupId'
     */
    @Test
    public void userGroupIdTest() {
        // TODO: test userGroupId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
