/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AllPermissionsAssignedForLocalTenantDTO;
import com.konfigthis.client.model.AllProfileAssignedForLocalTenantDTO;
import com.konfigthis.client.model.AllUserGroupsAssignedForLocalTenantDTO;
import com.konfigthis.client.model.LastLoginDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserGetAPIResponseDTO
 */
public class UserGetAPIResponseDTOTest {
    private final UserGetAPIResponseDTO model = new UserGetAPIResponseDTO();

    /**
     * Model tests for UserGetAPIResponseDTO
     */
    @Test
    public void testUserGetAPIResponseDTO() {
        // TODO: test UserGetAPIResponseDTO
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'accountEnabled'
     */
    @Test
    public void accountEnabledTest() {
        // TODO: test accountEnabled
    }

    /**
     * Test the property 'profiles'
     */
    @Test
    public void profilesTest() {
        // TODO: test profiles
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'userGroups'
     */
    @Test
    public void userGroupsTest() {
        // TODO: test userGroups
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    public void lastLoginTest() {
        // TODO: test lastLogin
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
