/*
 * Visier User Management APIs
 * Visier APIs for managing users within an organization
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AllPermissionsAssignedForLocalTenantDTO;
import com.konfigthis.client.model.AllProfileAssignedForLocalTenantDTO;
import com.konfigthis.client.model.AllUserGroupsAssignedForLocalTenantDTO;
import com.konfigthis.client.model.LastLoginDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UserGetAPIResponseDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UserGetAPIResponseDTO {
  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_EMPLOYEE_ID = "employeeId";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_ID)
  private String employeeId;

  public static final String SERIALIZED_NAME_ACCOUNT_ENABLED = "accountEnabled";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ENABLED)
  private Boolean accountEnabled;

  public static final String SERIALIZED_NAME_PROFILES = "profiles";
  @SerializedName(SERIALIZED_NAME_PROFILES)
  private AllProfileAssignedForLocalTenantDTO profiles;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private AllPermissionsAssignedForLocalTenantDTO permissions;

  public static final String SERIALIZED_NAME_USER_GROUPS = "userGroups";
  @SerializedName(SERIALIZED_NAME_USER_GROUPS)
  private AllUserGroupsAssignedForLocalTenantDTO userGroups;

  public static final String SERIALIZED_NAME_LAST_LOGIN = "lastLogin";
  @SerializedName(SERIALIZED_NAME_LAST_LOGIN)
  private LastLoginDTO lastLogin;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public UserGetAPIResponseDTO() {
  }

  public UserGetAPIResponseDTO userId(String userId) {
    
    
    
    
    this.userId = userId;
    return this;
  }

   /**
   * The unique identifier associated with the user.
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier associated with the user.")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    
    
    
    this.userId = userId;
  }


  public UserGetAPIResponseDTO username(String username) {
    
    
    
    
    this.username = username;
    return this;
  }

   /**
   * The user&#39;s username. This is typically the user&#39;s email, such as john@jupiter.com.
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user's username. This is typically the user's email, such as john@jupiter.com.")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    
    
    
    this.username = username;
  }


  public UserGetAPIResponseDTO displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * An identifiable name to display within Visier. For example, \&quot;John Smith\&quot;.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An identifiable name to display within Visier. For example, \"John Smith\".")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public UserGetAPIResponseDTO employeeId(String employeeId) {
    
    
    
    
    this.employeeId = employeeId;
    return this;
  }

   /**
   * If applicable, and if available, the user employee ID in the data.
   * @return employeeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If applicable, and if available, the user employee ID in the data.")

  public String getEmployeeId() {
    return employeeId;
  }


  public void setEmployeeId(String employeeId) {
    
    
    
    this.employeeId = employeeId;
  }


  public UserGetAPIResponseDTO accountEnabled(Boolean accountEnabled) {
    
    
    
    
    this.accountEnabled = accountEnabled;
    return this;
  }

   /**
   * If false, the user account is disabled.
   * @return accountEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If false, the user account is disabled.")

  public Boolean getAccountEnabled() {
    return accountEnabled;
  }


  public void setAccountEnabled(Boolean accountEnabled) {
    
    
    
    this.accountEnabled = accountEnabled;
  }


  public UserGetAPIResponseDTO profiles(AllProfileAssignedForLocalTenantDTO profiles) {
    
    
    
    
    this.profiles = profiles;
    return this;
  }

   /**
   * A list of objects representing the list of available profiles.
   * @return profiles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of objects representing the list of available profiles.")

  public AllProfileAssignedForLocalTenantDTO getProfiles() {
    return profiles;
  }


  public void setProfiles(AllProfileAssignedForLocalTenantDTO profiles) {
    
    
    
    this.profiles = profiles;
  }


  public UserGetAPIResponseDTO permissions(AllPermissionsAssignedForLocalTenantDTO permissions) {
    
    
    
    
    this.permissions = permissions;
    return this;
  }

   /**
   * A list of objects representing the user&#39;s permissions.
   * @return permissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of objects representing the user's permissions.")

  public AllPermissionsAssignedForLocalTenantDTO getPermissions() {
    return permissions;
  }


  public void setPermissions(AllPermissionsAssignedForLocalTenantDTO permissions) {
    
    
    
    this.permissions = permissions;
  }


  public UserGetAPIResponseDTO userGroups(AllUserGroupsAssignedForLocalTenantDTO userGroups) {
    
    
    
    
    this.userGroups = userGroups;
    return this;
  }

   /**
   * A list of objects representing the available user groups.
   * @return userGroups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of objects representing the available user groups.")

  public AllUserGroupsAssignedForLocalTenantDTO getUserGroups() {
    return userGroups;
  }


  public void setUserGroups(AllUserGroupsAssignedForLocalTenantDTO userGroups) {
    
    
    
    this.userGroups = userGroups;
  }


  public UserGetAPIResponseDTO lastLogin(LastLoginDTO lastLogin) {
    
    
    
    
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * An object that represents the time that the user last logged into Visier.
   * @return lastLogin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An object that represents the time that the user last logged into Visier.")

  public LastLoginDTO getLastLogin() {
    return lastLogin;
  }


  public void setLastLogin(LastLoginDTO lastLogin) {
    
    
    
    this.lastLogin = lastLogin;
  }


  public UserGetAPIResponseDTO email(String email) {
    
    
    
    
    this.email = email;
    return this;
  }

   /**
   * The user&#39;s email address.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user's email address.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    
    
    
    this.email = email;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UserGetAPIResponseDTO instance itself
   */
  public UserGetAPIResponseDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGetAPIResponseDTO userGetAPIResponseDTO = (UserGetAPIResponseDTO) o;
    return Objects.equals(this.userId, userGetAPIResponseDTO.userId) &&
        Objects.equals(this.username, userGetAPIResponseDTO.username) &&
        Objects.equals(this.displayName, userGetAPIResponseDTO.displayName) &&
        Objects.equals(this.employeeId, userGetAPIResponseDTO.employeeId) &&
        Objects.equals(this.accountEnabled, userGetAPIResponseDTO.accountEnabled) &&
        Objects.equals(this.profiles, userGetAPIResponseDTO.profiles) &&
        Objects.equals(this.permissions, userGetAPIResponseDTO.permissions) &&
        Objects.equals(this.userGroups, userGetAPIResponseDTO.userGroups) &&
        Objects.equals(this.lastLogin, userGetAPIResponseDTO.lastLogin) &&
        Objects.equals(this.email, userGetAPIResponseDTO.email)&&
        Objects.equals(this.additionalProperties, userGetAPIResponseDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, username, displayName, employeeId, accountEnabled, profiles, permissions, userGroups, lastLogin, email, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGetAPIResponseDTO {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    accountEnabled: ").append(toIndentedString(accountEnabled)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    userGroups: ").append(toIndentedString(userGroups)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("userId");
    openapiFields.add("username");
    openapiFields.add("displayName");
    openapiFields.add("employeeId");
    openapiFields.add("accountEnabled");
    openapiFields.add("profiles");
    openapiFields.add("permissions");
    openapiFields.add("userGroups");
    openapiFields.add("lastLogin");
    openapiFields.add("email");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UserGetAPIResponseDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UserGetAPIResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserGetAPIResponseDTO is not found in the empty JSON string", UserGetAPIResponseDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("employeeId") != null && !jsonObj.get("employeeId").isJsonNull()) && !jsonObj.get("employeeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeId").toString()));
      }
      // validate the optional field `profiles`
      if (jsonObj.get("profiles") != null && !jsonObj.get("profiles").isJsonNull()) {
        AllProfileAssignedForLocalTenantDTO.validateJsonObject(jsonObj.getAsJsonObject("profiles"));
      }
      // validate the optional field `permissions`
      if (jsonObj.get("permissions") != null && !jsonObj.get("permissions").isJsonNull()) {
        AllPermissionsAssignedForLocalTenantDTO.validateJsonObject(jsonObj.getAsJsonObject("permissions"));
      }
      // validate the optional field `userGroups`
      if (jsonObj.get("userGroups") != null && !jsonObj.get("userGroups").isJsonNull()) {
        AllUserGroupsAssignedForLocalTenantDTO.validateJsonObject(jsonObj.getAsJsonObject("userGroups"));
      }
      // validate the optional field `lastLogin`
      if (jsonObj.get("lastLogin") != null && !jsonObj.get("lastLogin").isJsonNull()) {
        LastLoginDTO.validateJsonObject(jsonObj.getAsJsonObject("lastLogin"));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserGetAPIResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserGetAPIResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserGetAPIResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserGetAPIResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<UserGetAPIResponseDTO>() {
           @Override
           public void write(JsonWriter out, UserGetAPIResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UserGetAPIResponseDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UserGetAPIResponseDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UserGetAPIResponseDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UserGetAPIResponseDTO
  * @throws IOException if the JSON string is invalid with respect to UserGetAPIResponseDTO
  */
  public static UserGetAPIResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserGetAPIResponseDTO.class);
  }

 /**
  * Convert an instance of UserGetAPIResponseDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

